### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'points'

### ISSUE THREAD

**Issue by lhthq** [PRBonn/LocNDF#11]
hi~ thanks for you work. when i want to train the model by: python3 scripts_pose_tracking/train_mapping.py -c config/config_mapping.yaml
i meet the issue as:
![2024-03-14 16-03-28 的屏幕截图](https://github.com/PRBonn/LocNDF/assets/62490307/a40300e1-c88c-4945-a091-ab2bfea0c9c6)
could you give me some advice? thank you!

**Comment by louis-wiesmann** [comment]
Hey, I guess you can checkout https://github.com/PRBonn/LocNDF/pull/10. Haven't time to review it but seems like it would fix the issue

**Comment by lhthq** [comment]
yes, it fixes the issue and works now.  thank you!
