### ISSUE TITLE
How to derive the equation (12) in the paper?

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/LocNDF#2]
Hi, thanks for your great work. May I ask for the derivation process of equation (12). How are Jaconbians calculated?
![image](https://github.com/PRBonn/LocNDF/assets/15854511/96939def-d7dc-4ec4-bf5f-e8c92212a56a)

**Comment by louis-wiesmann** [comment]
Here a derivation for row-wise Jacobian  :
![image](https://github.com/PRBonn/LocNDF/assets/76427549/886e2763-26d9-4d81-badf-cb27b7a559b4)

The squared brackets denote the skew symmetric matrix.

Be aware that depending on the definition of the error and Jacobian the some equations could be transposed or negative.  

This assumes a small Rotation. Therefore, we always transform the source points with the estimated transformation (or the initial guess)  after each iteration.

**Comment by DeepDuke** [comment]
TKS!
