### ISSUE TITLE
requirements.txt install error

### ISSUE THREAD

**Issue by Lee-JaeWon** [PRBonn/LocNDF#3]
I want to run your repository, but `requirements.txt` is not installing well.
Can you tell me the detailed conditions for your environment?
For example, it would be nice if you could tell me about ubuntu and python versions.
Packages in `requirements.txt` also have dependency errors.

I tried to install it in the following environment.

In docker,
`Ubuntu == 20.04`
`python == 3.9`
`pip install .`
`pip install -r requirements.txt`

Using anaconda on `Windows` also causes the same error as Ubuntu.
I appreciate your answer.

**Comment by Lee-JaeWon** [comment]
It was temporarily resolved in the following ways.
I hope it will be helpful when you do update the `README.md` file.

`Python == 3.9`
(from
```
update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
python -m pip install --upgrade pip
```
)
and
`Ubuntu == 20.04`

---

In `requirement.txt`, the dependency has been relaxed so that `pip` can install on its own.
```
torch==1.13.0
tqdm
scikit_image
easydict
open3d
numpy
Click
natsort
matplotlib
pytorch_lightning
PyYAML
scipy
```

Additionally, the following packages were also needed.
```
sudo apt-get install -y libgl1-mesa-glx libx11-dev
ldconfig
```

I hope it helps others.

**Comment by louis-wiesmann** [comment]
Thanks for noting. I've updated the readme and dependencies.
